# Generated by Django 4.2.1 on 2023-06-28 23:56

from django.db import migrations
import users.admin


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.admin.CustomUserManager()),
            ],
        ),
    ]
