name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region $AWS_REGION
    
    - name: Extract Version
      id: extract_version
      run: |
        COMMIT_MESSAGE=$(git log --merges --format=%B -n 1 $GITHUB_SHA)
        echo $COMMIT_MESSAGE
        echo "VERSION=$COMMIT_MESSAGE" >> $GITHUB_ENV


    - name: Build Docker image
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.$AWS_REGION.amazonaws.com
        docker build --tag="${{ secrets.AWS_ACCOUNT }}.dkr.ecr.$AWS_REGION.amazonaws.com/tukro_repo:$VERSION" .
        docker push "${{ secrets.AWS_ACCOUNT }}.dkr.ecr.$AWS_REGION.amazonaws.com/tukro_repo:$VERSION"

    - name: Create version
      run: |
        sh bin/change-version.sh $VERSION
        zip -r infra/deploy.zip infra/Dockerrun.aws.json
        aws s3 cp infra/deploy.zip s3://tukro-deploys/deploy-$VERSION.zip
        aws elasticbeanstalk create-application-version \
          --application-name tukro-app \
          --version-label $VERSION \
          --source-bundle S3Bucket=tukro-deploys,S3Key=deploy-$VERSION.zip

    - name: Update environment
      run: |
        aws elasticbeanstalk update-environment \        
          --environment-name tukro-app-env \
          --version-label $VERSION
